### ISSUE TITLE
some peoblems for install tendoo-cms in 3.0

### ISSUE THREAD

**Issue by cycold** [Blair2004/tendoo-cms#12]
install env: Mac os Yosemite; php `5.5.29`;  mysql `5.7.9 MySQL Community Server (GPL)`

1.should assign a value for `$config['sess_save_path']` in config.php and this path need writable permission

2.found a database error:
```
A Database Error Occurred
Error Number: 1171

All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

CREATE TABLE `tendoo_aauth_perm_to_group` ( `perm_id` int(11) unsigned DEFAULT NULL, `group_id` int(11) unsigned DEFAULT NULL, PRIMARY KEY (`perm_id`,`group_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Filename: modules/aauth/inc/setup.php

Line Number: 55
```

3.cannot create `database.php` file in application/config directory. so you should `chmod 757 config`

4.in first set up administrator page(after success install database) should check username must more than 6 character. Before I use admin as my administrator, But in sginin page use `admin`, The page give my error: cannot less than 6 character for name and email.....

so, if using mac, you should very carefully some directory permission. 

sorry , forgive me poor English,

**Comment by ebencarljo** [comment]
thanks for your review.. 
we'll fix all this very soon :)
