### ISSUE TITLE
On Install - mkdir(): Invalid path

### ISSUE THREAD

**Issue by Reconix** [Blair2004/tendoo-cms#25]
# So I get :

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 114

&

Message: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.

I got around this by doing db sessions instead of file based.

Thought I'd update just for anyone else :+1: 
https://github.com/Reconix/tendoo-cms/commit/a49fb5f263045388af2cbc9609e86ca4aea1726f

**Comment by Blair2004** [comment]
thank you for report. I'm checking that.

**Comment by Blair2004** [comment]
It has been fixed thank you @Reconix
