### ISSUE TITLE
Problem on wamp installation

### ISSUE THREAD

**Issue by fayri** [Blair2004/tendoo-cms#28]
Hi there,

May be only I'm facing this issue. But I've just downloaded the tendoo cms 3.0 and tried to install it on my local pc using wamp. Its a windows 10, 64bit and wamp is also 64bit. PHP version is 5.6.19.
When I first tried to install it show the error ;

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: libraries/Modules.php

Line Number: 300

Backtrace:

File: D:\wamp64\www\tendoocms30\application\libraries\Modules.php
Line: 300
Function: _error_handler

File: D:\wamp64\www\tendoocms30\application\core\Tendoo_Controller.php
Line: 57
Function: runDependency

File: D:\wamp64\www\tendoocms30\application\controllers\Dashboard.php
Line: 19
Function: __construct

File: D:\wamp64\www\tendoocms30\index.php
Line: 283
Function: require_once
----------------------------------

To fix this issue I changed the file D:\wamp64\www\tendoocms30\application\libraries\Modules.php ;
I've myself added this if condition and to get rid of this error. 
public static function runDependency()
     {
         global $Options;
         $modules   =   self::get();
         if($modules){
         foreach( $modules as $module ) {
             if( in_array( $module[ 'application' ][ 'namespace' ], ( array ) $Options[ 'actives_modules' ] ) ) {
                 self::checkDependency( $module[ 'application' ][ 'namespace' ] );
             }
         }
         }
     }

Afterwards there was no issue and everything works. But then whenever I try to use modules it never install a module. Frontend is always blank. 

Kindly check and suggest me some solution.

**Comment by fayri** [comment]
![image](https://cloud.githubusercontent.com/assets/28301305/25619894/f4999504-2f65-11e7-9acd-0019ca39695e.png)

you can see the screenshot from my local pc.
You can also notice that 2 menu links i.e. blog and pages, as shown in docs site, are missing.

**Comment by Blair2004** [comment]
Thank you for your interest

**Comment by Blair2004** [comment]
Let me check it and i'll give you a feedback why not a solution

**Comment by Blair2004** [comment]
Fixed
